# Here in this file, we are going to see the exception handling with a
# simple demo/example

try:
    res = 5/0 # Zero Division error
except:
    print(" An error occured, this message is from generic exception handling")